[package]
name = "file-io"
version = "0.1.0"
edition = "2024"
authors = ["Benjamin Massey <benjamin.w.massey@gmail.com>"]
description = "Example for simple file-based usage."

[dependencies]
image_outline = { path = "../.." }